//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenbank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Id { get; set; }
        public int PoolsId { get; set; }
        public string path { get; set; }
        public string filename { get; set; }
        public string displayname { get; set; }
        public string width { get; set; }
        public string heigth { get; set; }
        public string hsv { get; set; }
    
        public virtual Pools Pools { get; set; }
    }
}
