//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenbank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kacheln : Images
    {
        public int avgR { get; set; }
        public int avgG { get; set; }
        public int avgB { get; set; }
    }
}
